Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2022-03, with the labels that each got.

#166 Remove node version declaration in package.json
  package.json
  yarn.lock
Labels: dependencies

#175 Add 1.3 release notes
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-1.3.0.0.md
Labels: v1.3.0, backport 1.x

#184 Add backport documentation link
  DEVELOPER_GUIDE.md
Labels: documentation, backport 1.x

#162 Implemented support for cluster metrics monitors
  cypress/fixtures/sample_cluster_metrics_monitor.json
  cypress/integration/cluster_metrics_monitor_spec.js
  public/components/Flyout/flyouts/components/AlertsDashboardFlyoutComponent.js
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/ClusterMetricsMonitor.js
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/ClusterMetricsMonitor.test.js
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/__snapshots__/ClusterMetricsMonitor.test.js.snap
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/index.js
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/utils/clusterMetricsMonitorConstants.js
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/utils/clusterMetricsMonitorHelpers.js
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/utils/clusterMetricsMonitorHelpers.test.js
  public/pages/CreateMonitor/components/MonitorDefinitionCard/MonitorDefinitionCard.js
  public/pages/CreateMonitor/components/MonitorDefinitionCard/__snapshots__/MonitorDefinitionCard.test.js.snap
  public/pages/CreateMonitor/components/MonitorType/MonitorType.js
  public/pages/CreateMonitor/components/MonitorType/__snapshots__/MonitorType.test.js.snap
  public/pages/CreateMonitor/containers/AnomalyDetectors/__tests__/__snapshots__/AnomalyDetector.test.js.snap
  public/pages/CreateMonitor/containers/CreateMonitor/CreateMonitor.js
  public/pages/CreateMonitor/containers/CreateMonitor/__snapshots__/CreateMonitor.test.js.snap
  public/pages/CreateMonitor/containers/CreateMonitor/utils/__snapshots__/formikToMonitor.test.js.snap
  public/pages/CreateMonitor/containers/CreateMonitor/utils/constants.js
  public/pages/CreateMonitor/containers/CreateMonitor/utils/formikToMonitor.js
  public/pages/CreateMonitor/containers/CreateMonitor/utils/formikToMonitor.test.js
  public/pages/CreateMonitor/containers/CreateMonitor/utils/monitorToFormik.js
  public/pages/CreateMonitor/containers/CreateMonitor/utils/monitorToFormik.test.js
  public/pages/CreateMonitor/containers/DefineMonitor/DefineMonitor.js
  public/pages/CreateMonitor/containers/DefineMonitor/__snapshots__/DefineMonitor.test.js.snap
  public/pages/CreateMonitor/containers/MonitorDetails/MonitorDetails.js
  public/pages/CreateMonitor/containers/MonitorIndex/__snapshots__/MonitorIndex.test.js.snap
  public/pages/CreateTrigger/components/Action/Action.js
  public/pages/CreateTrigger/components/Action/utils/validate.js
  public/pages/CreateTrigger/components/AddActionButton/AddActionButton.js
  public/pages/CreateTrigger/components/AddTriggerButton/AddTriggerButton.js
  public/pages/CreateTrigger/components/BucketLevelTriggerQuery/BucketLevelTriggerQuery.js
  public/pages/CreateTrigger/components/TriggerEmptyPrompt/TriggerEmptyPrompt.js
  public/pages/CreateTrigger/components/TriggerQuery/TriggerQuery.js
  public/pages/CreateTrigger/components/TriggerQuery/__snapshots__/TriggerQuery.test.js.snap
  public/pages/CreateTrigger/containers/ConfigureActions/ConfigureActions.js
  public/pages/CreateTrigger/containers/ConfigureTriggers/ConfigureTriggers.js
  public/pages/CreateTrigger/containers/CreateTrigger/CreateTrigger/CreateTrigger.js
  public/pages/CreateTrigger/containers/CreateTrigger/utils/formikToTrigger.js
  public/pages/CreateTrigger/containers/CreateTrigger/utils/formikToTrigger.test.js
  public/pages/CreateTrigger/containers/CreateTrigger/utils/triggerToFormik.js
  public/pages/CreateTrigger/containers/DefineTrigger/DefineTrigger.js
  public/pages/Dashboard/components/AcknowledgeAlertsModal/AcknowledgeAlertsModal.js
  public/pages/Dashboard/components/AcknowledgeAlertsModal/__snapshots__/AcknowledgeAlertsModal.test.js.snap
  public/pages/MonitorDetails/components/MonitorOverview/utils/getOverviewStats.js
  public/pages/Monitors/containers/Monitors/Monitors.js
  public/utils/constants.js
  public/utils/validate.js
Labels: v1.3.0
