Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2022-11, with the labels that each got.

#357 Add 2.4 release notes
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.4.0.0.md
Labels: backport 2.x, backport 2.4

#349 Updated link to dashboards developer guide
  DEVELOPER_GUIDE.md
Labels: backport 2.x

#328 Fixed a bug that prevented the throttling settings from displaying for PER_ALERT bucket level trigger actions.
  public/pages/CreateTrigger/components/Action/actions/Message.js
Labels: backport 2.0, backport 2.x, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#363 Adjusted OpenSearch-Dashboards version used by test workflows.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.x
