Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2022-12, with the labels that each got.

#382 Avoid nesting search inside search when executing trigger condition for preview during create monitor
  public/pages/CreateTrigger/containers/ConfigureTriggers/ConfigureTriggers.js
Labels: backport 2.x

#379 Bumped loader-utils version to address dependabot alerts.
  package.json
  yarn.lock
Labels: backport 2.x

#375 [BUG] Issues in the UI above 200 destinations paging issue #195
  public/pages/CreateTrigger/components/Action/Action.js
  public/pages/CreateTrigger/containers/ConfigureActions/ConfigureActions.js
  public/pages/Destinations/containers/DestinationsList/DestinationsList.js
  public/utils/constants.js
Labels: backport 2.x

#385 Sort data by date for query visualization
  public/pages/CreateMonitor/components/VisualGraph/utils/helpers.js
Labels: backport 2.x

#396 Bumped 1.x to 1.3.7. Enabled windows unit tests.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  opensearch_dashboards.json
  package.json
Labels: backport 1.3

#373 Align all flyout components to be overlay kind and add close button X in header
  public/components/Flyout/flyouts/__snapshots__/flyouts.test.js.snap
  public/components/Flyout/flyouts/alertsDashboard.js
  public/components/Flyout/flyouts/components/AlertsDashboardFlyoutComponent.js
  public/pages/CreateMonitor/containers/CreateMonitor/CreateMonitor.js
  public/pages/Dashboard/components/AcknowledgeAlertsModal/AcknowledgeAlertsModal.js
  public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js
  public/pages/Dashboard/components/FindingsDashboard/findingsUtils.js
  public/pages/Dashboard/containers/Dashboard.js
  public/pages/MonitorDetails/containers/MonitorDetails.js
Labels: backport 2.x

#400 Bumped decode-uri-component version to address CVE-2022-38900.
  package.json
  yarn.lock
Labels: backport 2.x

#397 Fixed a bug that prevented the throttling settings from displaying for PER_ALERT bucket level trigger actions
  public/pages/CreateTrigger/components/Action/actions/Message.js
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#386 [BUG] Issues in the UI above 200 destinations #195
  public/pages/CreateTrigger/containers/ConfigureActions/ConfigureActions.js
  public/pages/Destinations/containers/DestinationsList/DestinationsList.js
  public/pages/Destinations/containers/DestinationsList/utils/constants.js
Labels: backport 1.x

#402 Keep monitor table cell width flexible; Check for whether monitor is enabled when displaying related action
  cypress/integration/query_level_monitor_spec.js
  public/pages/Destinations/components/NotificationsInfoCallOut/NotificationsInfoCallOut.js
  public/pages/Destinations/components/NotificationsInfoCallOut/__snapshots__/NotificationsInfoCallOut.test.js.snap
  public/pages/Destinations/containers/DestinationsList/__snapshots__/DestinationsList.test.js.snap
  public/pages/Monitors/containers/Monitors/Monitors.js
  public/pages/Monitors/containers/Monitors/__snapshots__/Monitors.test.js.snap
  public/pages/Monitors/containers/Monitors/utils/tableUtils.js
Labels: backport 2.x
