Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2023-01, with the labels that each got.

#437 Bumped version to 2.5.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  opensearch_dashboards.json
  package.json
Labels: backport 2.x

#440 2.5.0 release notes.
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.5.0.0.md
Labels: backport 2.x, backport 2.5

#443 Refactored the help text elements displayed when users access the destinations list page after destinations deprecation.
  public/pages/Destinations/components/DestinationsList/EmptyDestinations/EmptyDestinations.js
  public/pages/Destinations/components/FullPageNotificationsInfoCallOut/FullPageNotificationsInfoCallOut.js
  public/pages/Destinations/components/FullPageNotificationsInfoCallOut/FullPageNotificationsInfoCallOut.test.js
  public/pages/Destinations/components/FullPageNotificationsInfoCallOut/__snapshots__/FullPageNotificationsInfoCallOut.test.js.snap
  public/pages/Destinations/components/FullPageNotificationsInfoCallOut/index.js
  public/pages/Destinations/components/NotificationsInfoCallOut/NotificationsInfoCallOut.js
  public/pages/Destinations/components/NotificationsInfoCallOut/__snapshots__/NotificationsInfoCallOut.test.js.snap
  public/pages/Destinations/containers/DestinationsList/DestinationsList.js
  public/pages/Destinations/containers/DestinationsList/__snapshots__/DestinationsList.test.js.snap
  public/pages/Destinations/utils/constants.js
Labels: backport 2.1, backport 2.2, backport 2.4

#453 Fix CVE-2022-46175
  yarn.lock
Labels: backport 2.x, backport 2.5

#435 Updated MAINTAINERS.md format.
  MAINTAINERS.md
Labels: backport 2.x

#462 Refactored cypress and unit test workflows to use the 2.5.0 tag as the OSD repo reference.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.x
