Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2023-10, with the labels that each got.

#743 Support any channel types from Notification
  public/pages/CreateTrigger/components/Action/Action.js
  public/pages/CreateTrigger/components/Action/utils/constants.js
  public/pages/CreateTrigger/containers/ConfigureActions/ConfigureActions.js
  public/pages/CreateTrigger/containers/DefineCompositeLevelTrigger/TriggerNotifications.js
  public/pages/CreateTrigger/utils/constants.js
  public/pages/CreateTrigger/utils/helper.js
  public/services/NotificationService.ts
Labels: backport 2.x

#764 Drafted 2.11 release notes.
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#767 Removed "last updated by" sections from the UI.
  .github/workflows/cypress-workflow.yml
  cypress/integration/monitors_dashboard_spec.js
  public/pages/Destinations/containers/DestinationsList/utils/constants.js
  public/pages/MonitorDetails/components/MonitorOverview/__snapshots__/MonitorOverview.test.js.snap
  public/pages/MonitorDetails/components/MonitorOverview/utils/getOverviewStats.js
  public/pages/MonitorDetails/components/MonitorOverview/utils/getOverviewStats.test.js
  public/pages/Monitors/containers/Monitors/__snapshots__/Monitors.test.js.snap
  public/pages/Monitors/containers/Monitors/utils/tableUtils.js
Labels: backport 1.x, backport 2.0, backport 2.x, backport 2.1, backport 2.2, backport 2.3, backport 1.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.10, backport 2.11, backport 1.2

#789 Onboard Jenkins prod docker image to github actions
  .github/workflows/unit-tests-workflow.yml
Labels: enhancement, infrastructure, backport 2.x
