Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2023-11, with the labels that each got.

#820 Fix fetching of channels for composite monitors
  public/pages/CreateTrigger/containers/DefineCompositeLevelTrigger/TriggerNotifications.js
  yarn.lock
Labels: backport 2.x, backport 2.11

#828 Added 2.11.1 release notes.
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.11.0.0.md
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.11.1.0.md
Labels: backport 2.x, backport 2.11, v2.11.1

#827 Fixed bucket monitor groupBy/aggregation display bug.
  cypress/integration/alerts_dashboard_flyout_spec.js
  cypress/integration/bucket_level_monitor_spec.js
  cypress/integration/monitors_dashboard_spec.js
  public/pages/CreateMonitor/containers/CreateMonitor/utils/__snapshots__/formikToMonitor.test.js.snap
  public/pages/CreateMonitor/containers/CreateMonitor/utils/formikToMonitor.js
  public/pages/CreateTrigger/containers/ConfigureActions/ConfigureActions.js
  public/pages/Dashboard/utils/helpers.js
  public/pages/Dashboard/utils/helpers.test.js
Labels: backport 2.x, backport 2.9, backport 2.10, backport 2.11
