Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2023-07, with the labels that each got.

#574 Fixed a bug impacting data filter configuration through the visual editor.
  cypress/integration/bucket_level_monitor_spec.js
  cypress/integration/query_level_monitor_spec.js
  public/pages/CreateMonitor/components/MonitorExpressions/expressions/WherePopover.js
  public/pages/CreateMonitor/components/MonitorExpressions/expressions/utils/whereHelpers.js
  public/pages/CreateMonitor/components/MonitorTimeField/MonitorTimeField.js
  public/pages/CreateMonitor/components/MonitorTimeField/__snapshots__/MonitorTimeField.test.js.snap
Labels: backport 2.x, backport 2.7, backport 2.8

#609 Implemented support for configuring a cluster metrics monitor to call cat/indices, and cat/shards.
  cypress/integration/cluster_metrics_monitor_spec.js
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/utils/clusterMetricsMonitorConstants.js
Labels: backport 2.x, backport 2.9

#621 Added 2.9 release notes.
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9

#627 [Composite monitor] Add item_type field to monitor response
  server/services/MonitorService.js
Labels: backport 2.x, backport 2.9

#631 [Composite monitor] Added integration test for edit; fixed creation test
  cypress/integration/composite_level_monitor_spec.js
Labels: backport 2.x, backport 2.9

#634 [Composite monitor] Filtered associated alerts on the chained alerts details flyout
  public/pages/Dashboard/components/ChainedAlertDetailsFlyout/ChainedAlertDetailsFlyout.tsx
Labels: backport 2.x, backport 2.9

#630 Updated cypress test based on text changes.
  cypress/integration/cluster_metrics_monitor_spec.js
Labels: backport 2.x, backport 2.9

#639 Fix URI string generation logic.
  public/pages/CreateMonitor/components/ClusterMetricsMonitor/utils/clusterMetricsMonitorHelpers.test.js
  public/pages/CreateMonitor/containers/CreateMonitor/utils/formikToMonitor.js
Labels: backport 2.x, backport 2.9

#645 Fix monitor parse and alerts table
  public/pages/MonitorDetails/containers/MonitorDetails.js
  public/utils/contextMenu/monitors.ts
Labels: backport 2.x, backport 2.9

#649 Bumped tough-cookie, and semver versions.
  package.json
  yarn.lock
Labels: backport 2.9

#642 Upgrade the backport workflow
  .github/workflows/backport.yml
Labels: backport 2.x

#659 Optimize fetching of augment-vis saved objects
  public/utils/savedObjectHelper.tsx
Labels: backport 2.x, backport 2.9
