Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2024-09, with the labels that each got.

#1065 Added 2.17 release notes.
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.17.0.0.md
Labels: backport 2.x, v2.17.0

#1063 Side nav mds
  package.json
  public/pages/Main/Main.js
  public/pages/utils/constants.ts
  public/plugin.tsx
  yarn.lock
Labels: backport 2.x, backport 2.17

#1074 Fix CVE-2024-4067.
  package.json
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.17.0.0.md
  yarn.lock
Labels: backport 2.x, v2.17.0, backport 2.17

#1072 Added to 2.17 release notes.
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.17.0.0.md
Labels: backport 2.x, v2.17.0, backport 2.17

#996 Context aware alert analysis
  opensearch_dashboards.json
  public/app.js
  public/pages/Dashboard/containers/Dashboard.test.js
  public/pages/Dashboard/utils/tableUtils.js
  public/pages/Home/Home.js
  public/pages/Main/Main.js
  public/plugin.tsx
  public/services/services.ts
  public/types.ts
Labels: backport 2.x, v2.17.0

#1099 Fit and Finish UX changes Pt 2
  public/components/DataSourceAlertsCard/DataSourceAlertsCard.tsx
Labels: backport 2.x, backport 2.17

#1109 Added 2.17.1 release notes.
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.17.1.0.md
Labels: backport 2.x, backport 2.17, v2.17.1
