Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2024-10, with the labels that each got.

#1119 Support top N log pattern data in summary context provider for visual editor monitor
  public/pages/CreateMonitor/containers/CreateMonitor/utils/whereFilters.js
  public/pages/Dashboard/utils/constants.js
  public/pages/Dashboard/utils/helpers.js
  public/pages/Dashboard/utils/helpers.test.js
  public/pages/Dashboard/utils/tableUtils.js
Labels: backport 2.x

#1117 [Fit & Finish] Add width for recent alerts card
  public/utils/helpers.js
Labels: backport 2.x

#1124 Fix ui_metadata is not fetched when MDS client is used
  server/services/MonitorService.js
Labels: backport 2.x

#1127 MDS Bug fix when configuring a Trigger Action in Create Monitor
  public/pages/Dashboard/components/DashboardEmptyPrompt/DashboardEmptyPrompt.js
  public/pages/Dashboard/containers/Dashboard.js
  public/pages/Main/Main.js
Labels: backport 2.x

#1128 bug fix so that managed channels could be enabled
  public/pages/Dashboard/components/DashboardEmptyPrompt/DashboardEmptyPrompt.js
  public/pages/Dashboard/containers/Dashboard.js
Labels: backport 2.x

#1132 Added 2.18.0 release notes.
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.18.0.0.md
Labels: backport 2.x

#1131 fix: data source picker is remounted multiple times in alerts card
  public/components/DataSourceAlertsCard/DataSourceAlertsCard.tsx
Labels: backport 2.x, backport 2.17, backport 2.18

#1139 [BugFix] Pass isVisualEditorMonitor flag to downstream for verification
  public/pages/Dashboard/utils/tableUtils.js
Labels: backport 2.x, backport 2.18

#1143 fix: default data source
  public/pages/utils/constants.ts
  public/plugin.tsx
Labels: backport 2.x, backport 2.18

#1146 Make data source default cluster for alerts card
  public/components/DataSourceAlertsCard/DataSourceAlertsCard.tsx
Labels: backport 2.x, backport 2.18

#1149 Fix data source picker for alerts card
  public/components/DataSourceAlertsCard/DataSourceAlertsCard.tsx
Labels: backport 2.x, backport 2.18
