Repository opensearch-project/alerting-dashboards-plugin, pull requests merged in 2024-07, with the labels that each got.

#992 [Look&Feel] use standard paragraph size
  public/components/FeatureAnywhereContextMenu/AddAlertingMonitor/CreateNew/CreateNew.tsx
  public/components/Flyout/__snapshots__/Flyout.test.js.snap
  public/components/Flyout/flyouts/__snapshots__/flyouts.test.js.snap
  public/components/Flyout/flyouts/components/AlertsDashboardFlyoutComponent.js
  public/components/Flyout/flyouts/components/__snapshots__/AlertsDashboardFlyoutComponent.test.js.snap
  public/components/Flyout/flyouts/message.js
  public/components/Flyout/flyouts/messageFrequency.js
  public/components/Flyout/flyouts/triggerCondition.js
  public/pages/CreateMonitor/components/QueryPerformance/QueryPerformance.js
  public/pages/CreateTrigger/components/ActionEmptyPrompt/ActionEmptyPrompt.js
  public/pages/CreateTrigger/components/ActionEmptyPrompt/__snapshots__/ActionEmptyPrompt.test.js.snap
  public/pages/CreateTrigger/components/TriggerEmptyPrompt/TriggerEmptyPrompt.js
  public/pages/Dashboard/components/DashboardEmptyPrompt/DashboardEmptyPrompt.js
  public/pages/Dashboard/components/DashboardEmptyPrompt/__snapshots__/DashboardEmptyPrompt.test.js.snap
  public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js
  public/pages/Dashboard/containers/FindingsDashboard.js
  public/pages/Dashboard/containers/__snapshots__/Dashboard.test.js.snap
  public/pages/Destinations/components/FullPageNotificationsInfoCallOut/FullPageNotificationsInfoCallOut.js
  public/pages/Destinations/components/FullPageNotificationsInfoCallOut/__snapshots__/FullPageNotificationsInfoCallOut.test.js.snap
  public/pages/MonitorDetails/components/MonitorHistory/EmptyHistory/EmptyHistory.js
  public/pages/MonitorDetails/components/MonitorHistory/EmptyHistory/__snapshots__/EmptyHistory.test.js.snap
  public/pages/Monitors/components/MonitorEmptyPrompt/MonitorEmptyPrompt.js
  public/pages/Monitors/components/MonitorEmptyPrompt/__snapshots__/MonitorEmptyPrompt.test.js.snap
Labels: backport 2.x, v2.16.0

#994 [Look&Feel] use semantic header with correct size for page, modal and flyout
  cypress/integration/composite_level_monitor_spec.js
  public/components/ContentPanel/ContentPanel.js
  public/components/ContentPanel/__snapshots__/ContentPanel.test.js.snap
  public/components/FeatureAnywhereContextMenu/AddAlertingMonitor/AddAlertingMonitor.tsx
  public/components/FeatureAnywhereContextMenu/AssociatedMonitors/AssociatedMonitors.tsx
  public/components/FeatureAnywhereContextMenu/AssociatedMonitors/__snapshots__/AssociatedMonitors.test.js.snap
  public/components/Flyout/flyouts/__snapshots__/flyouts.test.js.snap
  public/components/Flyout/flyouts/triggerCondition.js
  public/pages/CreateMonitor/components/QueryPerformance/QueryPerformance.js
  public/pages/CreateMonitor/components/QueryPerformance/__snapshots__/QueryPerformance.test.js.snap
  public/pages/CreateMonitor/components/VisualGraph/__snapshots__/VisualGraph.test.js.snap
  public/pages/CreateMonitor/containers/CreateMonitor/CreateMonitor.js
  public/pages/CreateMonitor/containers/WorkflowDetails/__snapshots__/WorkflowDetails.test.js.snap
  public/pages/Dashboard/containers/Dashboard.js
  public/pages/Dashboard/containers/__snapshots__/Dashboard.test.js.snap
  public/pages/MonitorDetails/components/MonitorOverview/__snapshots__/MonitorOverview.test.js.snap
  public/pages/MonitorDetails/containers/MonitorDetails.js
Labels: v2.16.0

#997 [Look&Feel] Use small EuiTabs across the board
  public/components/Flyout/flyouts/components/AlertsDashboardFlyoutComponent.js
  public/pages/Home/Home.js
  public/pages/Home/__snapshots__/Home.test.js.snap
  public/pages/MonitorDetails/containers/MonitorDetails.js
Labels: backport 2.x, v2.16.0

#1003 Plugin Version decoupling for MDS support
  opensearch_dashboards.json
  public/pages/Main/Main.js
Labels: backport 2.x

#1004 [Look&Feel] apply missing pattern guidance to Alerting experience
  cypress/integration/composite_level_monitor_spec.js
  public/components/Flyout/flyouts/__snapshots__/flyouts.test.js.snap
  public/components/Flyout/flyouts/alertsDashboard.js
  public/pages/Monitors/components/MonitorActions/MonitorActions.js
Labels: backport 2.x

#1007 side nav changes for alerting
  cypress/integration/bucket_level_monitor_spec.js
  cypress/integration/query_level_monitor_spec.js
  public/app.js
  public/pages/Home/Home.js
  public/pages/Main/Main.js
  public/plugin.tsx
  utils/constants.js
Labels: backport 2.x

#1012 [Look&Feel] Adjust helper text size across monitor page
  public/pages/CreateMonitor/components/MonitorExpressions/__snapshots__/MonitorExpressions.test.js.snap
  public/pages/CreateMonitor/components/MonitorExpressions/expressions/__snapshots__/WhereExpression.test.js.snap
  public/utils/helpers.js
Labels: backport 2.x, v2.16.0

#1019 added release notes for 2.16
  release-notes/opensearch-alerting-dashboards-plugin.release-notes-2.16.0.0.md
Labels: backport 2.x

#1023 [Manual][Backport 2.16][Look&Feel] apply missing pattern guidance to Alerting experience (#1004)
  cypress/integration/composite_level_monitor_spec.js
  public/components/Flyout/flyouts/__snapshots__/flyouts.test.js.snap
  public/components/Flyout/flyouts/alertsDashboard.js
  public/pages/Monitors/components/MonitorActions/MonitorActions.js
Labels: v2.16.0

#1024 [CVE-2024-4068] Pinned package version for braces
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.16

#1027 Fixed cypress tests.
  cypress/integration/bucket_level_monitor_spec.js
  cypress/integration/query_level_monitor_spec.js
Labels: backport 2.x, backport 2.13, backport 2.14, backport 2.15, backport 2.16

#1028 [navigation]fix: remove the workspaceAvailability field to make alert visible within workspace
  public/plugin.tsx
Labels: backport 2.x, backport 2.16
